name: CI/CD

on:
  push:
    branches:
      - main

jobs:
  checkout:
    runs-on: self-hosted
    steps:
      - name: checkout
        uses: actions/checkout@v4
      
      - name: Set vars
        run: |
          echo "short_sha=$(git rev-parse --short ${{ github.sha }})" >> $GITHUB_OUTPUT
          echo "build_time=$(date +'%Y%m%d-%s')" >> $GITHUB_OUTPUT


  configureAWS:
    needs: [checkout]
    runs-on: self-hosted
    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ASIAT43JXY7MOEO6KUEI
          aws-secret-access-key: QZTYRG5yeQYNWB7Wnpey4aISZjd7rdS+I9AFCMJx
          aws-region: us-east-1
          aws-session-token: IQoJb3JpZ2luX2VjEEUaCXVzLXdlc3QtMiJHMEUCIQCQKfhMiCNvwNqNglbXzgJitruDYzbyVnrcGwyAx6Qe+QIgEE4alOMNtfZDMChu/VSDs4FjSQSsuh2oqTsIoSU/bLUqvgII7v//////////ARAAGgwyNjgxMjAzNDQ1MzYiDAkI/2qWUO7Kox/0+SqSAitSXy1NIFUbZO/zf6JAC78br9q6/nsjsXkKEirHbqKU3+Sw+Cw+76AFF7xHn+dUCGZxuRGgHYqJs7Dg7SIgy+kOYAbEqEI+HT0dKhnwCa5r5zfa5ZZikZgi/ow/OAW/rqt47TgPyVwEjQhUXDGE2kHLEQHLKgDskIfBfr2SLAsyWC+l6pWgEWf2p/Lz3olOadUS5rY4copYwNXxb7wZwGZKplXcBk0PVgroyIIWaYgu0a0C2zqRquPCWzVR1QZDKj3WoFVZf6/FnF73rp7WCwqGzM6R6dGj+O05wWhU6lBROVT1Z/MTniAZpsyBfDzl7Y2dNhFLhgi/Zf6Ue+WZNRFIE5cYxE1tzY2V9ddWcSZJLTowqsT1swY6nQENYEDTRl5A567Zt5ImG08YUVxBoMCG+8xmMWa5LSi4mye28WUanwnM/SeLvqeE9CbwDB7/MeIDR6ZASY9dBJCQ8f3MsNPqTe8nkeGxA6pTzyPa/9qjLJTCobC9jWiRQSsdffULYOXqpJV+EcEmpRmMKZvJZ5igTMD8K+0m2qjQp3zrwxLv415k5B55BmZhWbAb6CIbORtm3IEje9aM

  build:
    needs: [checkout,configureAWS]
    runs-on: self-hosted
    steps:
      - name: Install dependencies
        run: npm install
        
      - name: Run tests
        run: |
          export CHROME_BIN=/usr/bin/google-chrome
          ng test --code-coverage

      - name: SonarQube scan
        run: |
          npx sonar-scanner \
            -Dsonar.projectKey=xcoinDashboard \
            -Dsonar.organization=xcoinDashboard \
            -Dsonar.projectVersion=1.0 \
            -Dsonar.host.url=http://ec2-107-22-222-188.compute-1.amazonaws.com:9000 \
            -Dsonar.login=625d04f4150d4368738baf4abe7934b04bce9c2f \
            -Dsonar.sources=src \
            -Dsonar.tests=src \
            -Dsonar.exclusions=**/*.spec.ts \
            -Dsonar.test.inclusions=**/*.spec.ts \
            -Dsonar.javascript.lcov.reportPaths=coverage/lcov.info
      
      - name: Build application
        run: npm run build --prod

      - name: Package application
        run: |
          rm -rf runner/dist
          mv dist runner/
          pwd
          cd runner/
          rm package-lock.json
          zip -r xcoindashboard-${{ steps.set-vars.outputs.short_sha }}-${{ steps.set-vars.outputs.build_time }}.zip .
          mv xcoindashboard-${{ steps.set-vars.outputs.short_sha }}-${{ steps.set-vars.outputs.build_time }}.zip /home/ubuntu/actions-runner/_work/xCoin-Dashboard-UI/xCoin-Dashboard-UI/

  deploy:
    needs: [build]
    runs-on: self-hosted
    steps:
      - name: Deploy application to AWS Elastic Beanstalk
        uses: einaregilsson/beanstalk-deploy@v22
        with:
          aws_access_key: ASIAT43JXY7MOEO6KUEI
          aws_secret_key: QZTYRG5yeQYNWB7Wnpey4aISZjd7rdS+I9AFCMJx
          aws_session_token: IQoJb3JpZ2luX2VjEEUaCXVzLXdlc3QtMiJHMEUCIQCQKfhMiCNvwNqNglbXzgJitruDYzbyVnrcGwyAx6Qe+QIgEE4alOMNtfZDMChu/VSDs4FjSQSsuh2oqTsIoSU/bLUqvgII7v//////////ARAAGgwyNjgxMjAzNDQ1MzYiDAkI/2qWUO7Kox/0+SqSAitSXy1NIFUbZO/zf6JAC78br9q6/nsjsXkKEirHbqKU3+Sw+Cw+76AFF7xHn+dUCGZxuRGgHYqJs7Dg7SIgy+kOYAbEqEI+HT0dKhnwCa5r5zfa5ZZikZgi/ow/OAW/rqt47TgPyVwEjQhUXDGE2kHLEQHLKgDskIfBfr2SLAsyWC+l6pWgEWf2p/Lz3olOadUS5rY4copYwNXxb7wZwGZKplXcBk0PVgroyIIWaYgu0a0C2zqRquPCWzVR1QZDKj3WoFVZf6/FnF73rp7WCwqGzM6R6dGj+O05wWhU6lBROVT1Z/MTniAZpsyBfDzl7Y2dNhFLhgi/Zf6Ue+WZNRFIE5cYxE1tzY2V9ddWcSZJLTowqsT1swY6nQENYEDTRl5A567Zt5ImG08YUVxBoMCG+8xmMWa5LSi4mye28WUanwnM/SeLvqeE9CbwDB7/MeIDR6ZASY9dBJCQ8f3MsNPqTe8nkeGxA6pTzyPa/9qjLJTCobC9jWiRQSsdffULYOXqpJV+EcEmpRmMKZvJZ5igTMD8K+0m2qjQp3zrwxLv415k5B55BmZhWbAb6CIbORtm3IEje9aM
          region: us-east-1
          application_name: xcoindashboard 
          environment_name: xcoindashboard-env
          version_label: ${{ github.run_id }} 
          deployment_package: xcoindashboard-${{ steps.set-vars.outputs.short_sha }}-${{ steps.set-vars.outputs.build_time }}.zip
