name: CI/CD

on:
  push:
    branches:
      - main

jobs:
  checkout:
    runs-on: self-hosted
    steps:
      - name: checkout
        uses: actions/checkout@v4
      
      - name: Set vars
        run: |
          echo "short_sha=$(git rev-parse --short ${{ github.sha }})" >> $GITHUB_OUTPUT
          echo "build_time=$(date +'%Y%m%d-%s')" >> $GITHUB_OUTPUT


  configureAWS:
    needs: [checkout]
    runs-on: self-hosted
    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ASIAWS3QKD3DPSPXQ4AS
          aws-secret-access-key: My5JOKpfg54WceKMsXjiMn32LZmaKC3IVKPRETfQ
          aws-region: us-east-1
          aws-session-token: IQoJb3JpZ2luX2VjEBUaCXVzLXdlc3QtMiJIMEYCIQDf65gVwCMqQSafbIXXvCVZeBz9LEqJFfsoGNvV9jg3AQIhANFTiKvea4i+TwVvdLZDw/tHVYxCtGWtfRj2x8M4Ou9SKr0CCI7//////////wEQARoMNDUyODE3NzIzMDc4IgwbcM1NJFVGD7Rhh+YqkQLfQgKaYLO3R03l3SkZfawRMLD05mYsLzJkGh1+6ZanYEF+VdVlLwLaVRl9QcVBkndI3fI2pi8edHJVgCWFMVXZ9NjiDx00Cze7hjx9DlkQoJSKJelo/yoHN9nXiTHpuxexPrfiWPK5iH9VjZ6DEO2u6qZjdoLB4Pca2SPBrz1/WDIgx+rVrgCPH3axVtiX7kPbZbUa1oRpc1+BPbhmM/oe7fMtvSeVIikeEN6/8ckm5y2tzhtm+S5AhGFfzl/OUU0iDBNf2EBgN/5u3Q7+g5GIE1lVb0KnuKUD7yg2USxp95tzteQxjpf7WU+qJRNY5O3/z44BnyAQh5abMhsq9ciEX6dErUq/SFMUHbn7Xxo/Ws0wrJfCsgY6nAFx84Tgdl7tG9KYi2xwKeocYX1/dBmkv9Jzeo1lRkNIW0L506HfFeNVVw3HnkAhdgp6Klub0WPmmL/INGa9QE2pWnkrfVDLGgLWUVz2K6Q6TGMIxjAx+6M6TVuU4SEjM/q1wPTnj0bkm3IpDPlnm1FqYZh2SbWpuNAOmThaSK9qwmyjcLjnNjeJidZenuBD8/40Sz2OOVqe9+40BYM=

  build:
    needs: [checkout,configureAWS]
    runs-on: self-hosted
    steps:
      - name: Install dependencies
        run: npm install
      
      - name: Build application
        run: npm run build --prod

      - name: Package application
        run: |
          mv dist runner/
          pwd
          cd runner/
          rm package-lock.json
          zip -r xwallet-${{ steps.set-vars.outputs.short_sha }}-${{ steps.set-vars.outputs.build_time }}.zip .
          mv xwallet-${{ steps.set-vars.outputs.short_sha }}-${{ steps.set-vars.outputs.build_time }}.zip /home/ubuntu/actions-runner/_work/xCoin-Dashboard-UI/xCoin-Dashboard-UI/

  deploy:
    needs: [build]
    runs-on: self-hosted
    steps:
      - name: Deploy application to AWS Elastic Beanstalk
        uses: einaregilsson/beanstalk-deploy@v22
        with:
          aws_access_key: ASIAWS3QKD3DPSPXQ4AS
          aws_secret_key: My5JOKpfg54WceKMsXjiMn32LZmaKC3IVKPRETfQ
          aws_session_token: IQoJb3JpZ2luX2VjEBUaCXVzLXdlc3QtMiJIMEYCIQDf65gVwCMqQSafbIXXvCVZeBz9LEqJFfsoGNvV9jg3AQIhANFTiKvea4i+TwVvdLZDw/tHVYxCtGWtfRj2x8M4Ou9SKr0CCI7//////////wEQARoMNDUyODE3NzIzMDc4IgwbcM1NJFVGD7Rhh+YqkQLfQgKaYLO3R03l3SkZfawRMLD05mYsLzJkGh1+6ZanYEF+VdVlLwLaVRl9QcVBkndI3fI2pi8edHJVgCWFMVXZ9NjiDx00Cze7hjx9DlkQoJSKJelo/yoHN9nXiTHpuxexPrfiWPK5iH9VjZ6DEO2u6qZjdoLB4Pca2SPBrz1/WDIgx+rVrgCPH3axVtiX7kPbZbUa1oRpc1+BPbhmM/oe7fMtvSeVIikeEN6/8ckm5y2tzhtm+S5AhGFfzl/OUU0iDBNf2EBgN/5u3Q7+g5GIE1lVb0KnuKUD7yg2USxp95tzteQxjpf7WU+qJRNY5O3/z44BnyAQh5abMhsq9ciEX6dErUq/SFMUHbn7Xxo/Ws0wrJfCsgY6nAFx84Tgdl7tG9KYi2xwKeocYX1/dBmkv9Jzeo1lRkNIW0L506HfFeNVVw3HnkAhdgp6Klub0WPmmL/INGa9QE2pWnkrfVDLGgLWUVz2K6Q6TGMIxjAx+6M6TVuU4SEjM/q1wPTnj0bkm3IpDPlnm1FqYZh2SbWpuNAOmThaSK9qwmyjcLjnNjeJidZenuBD8/40Sz2OOVqe9+40BYM=
          region: us-east-1
          application_name: xcoinwallet 
          environment_name: xcoin-wallet-prod
          version_label: ${{ github.run_id }} 
          deployment_package: xwallet-${{ steps.set-vars.outputs.short_sha }}-${{ steps.set-vars.outputs.build_time }}.zip
