name: CI/CD

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy
    runs-on: self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ASIAWS3QKD3DAIVYM2RB
          aws-secret-access-key: 998MjulRFNMtmJdSpm8AXZEiAKsQlEqK6uUgUfHk
          aws-region: us-east-1
          aws-session-token: IQoJb3JpZ2luX2VjECoaCXVzLXdlc3QtMiJHMEUCIBfayXPpHgYqAxRJzaN/iTV/kLO9A3wLKEhIQeftXfnoAiEAgoKGYCJPpAn1OBrvgGEuVdOCUt58wFz7h7nwAL87ZxsqvQIIk///////////ARABGgw0NTI4MTc3MjMwNzgiDIxhXg7IvD+7R0HjOCqRAhDDBMNsoQd4vhFS7Jq+2sSG3krxhC8JuarwetFF98bbRh6GYgN2wYnRqeycAnJmzN3NCQJdi9MIDrAnEdAvhGDvGEeiWpjpoECxcI4Msn2/vn5e3mRR3XA8BT7EWO26rTz0Uh7DBsmOE8hOkp4yx8wJvKtyl4O3QuSvB6FrGV6uFMSgZ5ND8UmUO+R/+YtXZPUUZFqMkfHPKg9NEqIgRJStlPPhFM8b4NTjcLIYLNm/cTqayWZIp+9ixbfAkZCWjaHcyiBytIg93Tf12ssnOnsA3/FqHIV4fF9ojvlSIRDY63mQhP7w9/QS3UIMOeU3FjTPrbBtRSusrk05MGS7dE0HQzVu0ibqYp2QPkslXZ6gLDCQzo6yBjqdAeuWAR9q8dmQuhstpmCs1c2bYEQGzL1rYEntQf/nvE44ta0MyehMn7mfYTie34Ny0HJOgo1IqRNpszEyHFcUwudvjDfmYiNTcRGY7wMj9H37VdeeStp142JEWiDP15u7LSYrO4YwNRpm5/wkvGBUXUuFucX0QuR6/KZuR/w+v/Ztf72BFcWNVFhLpjQP38qgBrqvEwum4Vkeimdln+I=
          
      - name: Set vars
        id: set-vars
        run: |
          echo "short_sha=$(git rev-parse --short ${{ github.sha }})" >> $GITHUB_OUTPUT
          echo "build_time=$(date +'%Y%m%d-%s')" >> $GITHUB_OUTPUT

      - name: Install
        id: install
        run: npm install
      
      - name: Build
        id: build
        run: |
          npm run build --prod
          mv dist runner/
          pwd
          cd runner/
          rm package-lock.json
          zip -r xwallet-${{ steps.set-vars.outputs.short_sha }}-${{ steps.set-vars.outputs.build_time }}.zip .
          mv xwallet-${{ steps.set-vars.outputs.short_sha }}-${{ steps.set-vars.outputs.build_time }}.zip /home/ubuntu/actions-runner/_work/xCoin-Dashboard-UI/xCoin-Dashboard-UI/

      - name: Deploy application to AWS ElasticBeanstalk
        uses: einaregilsson/beanstalk-deploy@v22
        with:
          aws-access-key: ASIAWS3QKD3DAIVYM2RB
          aws-secret-key: 998MjulRFNMtmJdSpm8AXZEiAKsQlEqK6uUgUfHk
          aws-session-token: IQoJb3JpZ2luX2VjECoaCXVzLXdlc3QtMiJHMEUCIBfayXPpHgYqAxRJzaN/iTV/kLO9A3wLKEhIQeftXfnoAiEAgoKGYCJPpAn1OBrvgGEuVdOCUt58wFz7h7nwAL87ZxsqvQIIk///////////ARABGgw0NTI4MTc3MjMwNzgiDIxhXg7IvD+7R0HjOCqRAhDDBMNsoQd4vhFS7Jq+2sSG3krxhC8JuarwetFF98bbRh6GYgN2wYnRqeycAnJmzN3NCQJdi9MIDrAnEdAvhGDvGEeiWpjpoECxcI4Msn2/vn5e3mRR3XA8BT7EWO26rTz0Uh7DBsmOE8hOkp4yx8wJvKtyl4O3QuSvB6FrGV6uFMSgZ5ND8UmUO+R/+YtXZPUUZFqMkfHPKg9NEqIgRJStlPPhFM8b4NTjcLIYLNm/cTqayWZIp+9ixbfAkZCWjaHcyiBytIg93Tf12ssnOnsA3/FqHIV4fF9ojvlSIRDY63mQhP7w9/QS3UIMOeU3FjTPrbBtRSusrk05MGS7dE0HQzVu0ibqYp2QPkslXZ6gLDCQzo6yBjqdAeuWAR9q8dmQuhstpmCs1c2bYEQGzL1rYEntQf/nvE44ta0MyehMn7mfYTie34Ny0HJOgo1IqRNpszEyHFcUwudvjDfmYiNTcRGY7wMj9H37VdeeStp142JEWiDP15u7LSYrO4YwNRpm5/wkvGBUXUuFucX0QuR6/KZuR/w+v/Ztf72BFcWNVFhLpjQP38qgBrqvEwum4Vkeimdln+I=
          region: us-east-1
          application_name: xcoinwallet 
          environment_name: xcoin-wallet-prod
          version_label: ${{ github.run_id }} 
          deployment_package: xwallet-${{ steps.set-vars.outputs.short_sha }}-${{ steps.set-vars.outputs.build_time }}.zip